# GitHub Sponsors & Funding
# Uncomment and add your funding platforms

# GitHub Sponsors
# github: [tutaki304]

# Patreon
# patreon: your-patreon

# Ko-fi
# ko_fi: your-kofi

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/your-username']

# PayPal
# custom: ['https://paypal.me/your-paypal']
